name: Build and Package Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read

env:
  PROJECT_NAME: OutSystems.Bogus
  PRODUCT_NAME: Bogus

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.sln

    - name: Run Tests
      run: |
        dotnet test ${{ env.PROJECT_NAME }}.UnitTests/${{ env.PROJECT_NAME }}.UnitTests.csproj \
        --configuration Release \
        --no-restore \
        --nologo \
        --collect:"XPlat Code Coverage" \
        --results-directory ./coverage

    - name: Report Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        format: markdown
        output: both

    - name: Write Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

  release:
    name: Package and Release
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: '8.0.x'

    - name: Get Version from Tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Publish App
      run: |
        dotnet publish ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj \
        -c Release \
        -r linux-x64 \
        --self-contained false \
        -o ./publish

    - name: Create Versioned Zip
      run: |
        cd ./publish
        zip -r ../${{ env.PRODUCT_NAME }}_${{ steps.get_version.outputs.VERSION }}.zip .
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
      with:
        files: ${{ env.PRODUCT_NAME }}_${{ steps.get_version.outputs.VERSION }}.zip
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
